# .github/workflows/format.yml
name: Format

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.9
        with:
          architecture: "x64"
          distribution: "full"
          variant: "CS"
          version: "8.9"

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install treefmt
        run: nix-env -iA nixpkgs.treefmt

      - name: Install fmt
        run: raco pkg install -D --deps search-auto fmt

      - name: Format
        run: treefmt

      - name: Commit
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git commit -am "chore: format"
            git push
          fi
